apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-001
  namespace: minio
  labels:
    type: local-hdd-minio
spec:
  capacity:
    storage: 5Gi
  storageClassName: slow
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
  nfs:
    # mountするNFSサーバーのディレクトリ
    path: /tmp/k8svp/minio/v001
    # NFSサーバーのホスト
    server: 192.168.56.100
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-002
  namespace: minio
  labels:
    type: local-hdd-minio
spec:
  capacity:
    storage: 5Gi
  storageClassName: slow
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
  nfs:
    # mountするNFSサーバーのディレクトリ
    path: /tmp/k8svp/minio/v002
    # NFSサーバーのホスト
    server: 192.168.56.100
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-003
  namespace: minio
  labels:
    type: local-hdd-minio
spec:
  capacity:
    storage: 5Gi
  storageClassName: slow
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
  nfs:
    # mountするNFSサーバーのディレクトリ
    path: /tmp/k8svp/minio/v003
    # NFSサーバーのホスト
    server: 192.168.56.100
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-004
  namespace: minio
  labels:
    type: local-hdd-minio
spec:
  capacity:
    storage: 5Gi
  storageClassName: slow
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
  nfs:
    # mountするNFSサーバーのディレクトリ
    path: /tmp/k8svp/minio/v004
    # NFSサーバーのホスト
    server: 192.168.56.100
