apiVersion: v1
kind: Pod
metadata:
  name: kafka-influxdb
  labels:
    app: kafka-influxdb
spec:
  containers:
  - name: kafka-influxdb
    image: influxdb:2.5.1-alpine
    imagePullPolicy: Always
    env:
    - name: INFLUXDB_ADMIN_ENABLED
      value: "true"

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-influxdb
spec:
  selector:
    app: kafka-influxdb
  type: NodePort
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      nodePort: 30711
    - name: db
      port: 8086
      targetPort: 8086
      nodePort: 30712

