### zookeeper ###
apiVersion: v1
kind: Service
metadata:
  name: kafka-zookeeper
spec:
  type: NodePort
  ports:
  - port: 2181
    targetPort: 2181
    nodePort: 32181
  selector:
    app: kafka-zookeeper

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-zookeeper
  labels:
    app: kafka-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-zookeeper
  template:
    metadata:
      labels:
        app: kafka-zookeeper
    spec:
      imagePullSecrets:
      - name: local-docker-nexus
      containers:
      - name: zookeeper
        image: nexus.vbox.local:9001/sea-zookeeper:latest
        imagePullPolicy: IfNotPresent
#        resources:
#          limits:
#            cpu: 1000m
#            memory: 1Gi
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        ports:
        - containerPort: 2181
          protocol: TCP
      dnsConfig:
        options:
        - name: ndots
          value: "1"